import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { useEffect, useState } from "react";
import api from "./api/api";
import Link from "next/link";

  


export default function Home() {
  
  return (
    <>
        <Head>
          <title>Urna eletrônica</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
            crossOrigin="anonymous"
          />
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossOrigin="anonymous"
          ></script>
        </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.do}>
          <ul>
            <li><Link href="/vote/">Quero Votar</Link></li>
            <li><Link href="/report/">Quero ver resultados</Link></li>
          </ul>
        </div>
      </main>
      <Footer/>
    </>
  );
}
